name: Android CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  # Allows the EndBug/add-and-commit step to commit the package manager changes,
  # adding the AppMap language library and configuration file appmap.yml.
  # Once the EndBug/add-and-commit is removed, this permission can be removed, 
  # unless you need it for other reasons.
  contents: write

  # Allows the getappmap/archive-action to write a PR comment with the 
  # AppMap configuration status.
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - name: set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    # Begin AppMap CI language agent installation
    # This snippet can be safely removed once the AppMap language agent has been
    # added to the project dependencies, and appmap.yml has been created.
    - name: Install AppMap tools
      id: install-appmap
      uses: getappmap/install-action@v1
      with:
        project-type: gradle
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "ci: Add AppMap language agent and appmap.yml"
    # End AppMap CI language agent installation
    - name: Check Snippets
      run: python scripts/checksnippets.py
    - name: Copy mock google_services.json
      run: ./copy_mock_google_services_json.sh
    - name: Run tests
      run: ./gradlew appmap test
    - name: Build with Gradle (Pull Request)
      run: ./build_pull_request.sh
      if: github.event_name == 'pull_request'
    - name: Build with Gradle (Push)
      run: ./gradlew clean ktlint build
      if: github.event_name != 'pull_request'